export const availableProducts = [
  { productName: "WORKFLOWAI", id: 11 },
  { productName: "TEAMMANAGEMENT", id: 12 },
  { productName: "WIFIQRCODE", id: 13 },
  { productName: "SALESAGENTLOGIN", id: 14 },
  { productName: "LEGALZARD", id: 15 },
  { productName: "USEREXPERIENCELIVE", id: 16 },
  { productName: "SOCIALMEDIAAUTOMATION", id: 17 },
  { productName: "LIVINGLABSCALES", id: 18 },
  { productName: "LOGOSCAN", id: 19 },
  { productName: "LIVINGLABMONITORING", id: 20 },
  { productName: "PERMUTATIONCALCULATOR", id: 21 },
  { productName: "SECUREREPOSITORIES", id: 22 },
  { productName: "SECUREDATA", id: 23 },
  { productName: "CUSTOMEREXPERIENCE", id: 24 },
  { productName: "DOWELLCSC", id: 25 },
  { productName: "LIVINGLABCHAT", id: 26 },
  { productName: "SALESAGENT", id: 27 },
  { productName: "LOGIN", id: 28 },
  { productName: "PUBLIC_QR", id: 29 },
];
