# Generated by Django 4.1.7 on 2023-08-19 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(default='4mhR3', max_length=200)),
                ('is_staff', models.BooleanField(default=False)),
                ('session_id', models.CharField(max_length=32)),
                ('organization', models.CharField(default='NO_LOGIN', max_length=200)),
                ('userID', models.CharField(default='NO_LOGIN', max_length=200)),
                ('dowell_logged_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('room_count', models.IntegerField()),
                ('organization', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room_name', models.CharField(blank=True, max_length=200, null=True)),
                ('room_id', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_product', models.CharField(blank=True, max_length=20, null=True)),
                ('sender_portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_support.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('side', models.BooleanField(default=False)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image')], default='TEXT', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_support.portfolio')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_support.room')),
            ],
        ),
    ]
