# Generated by Django 4.1.7 on 2023-08-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0002_room_link_id_alter_portfolio_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='generated_by_QR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='rm_link',
            field=models.URLField(default='https://100096.pythonanywhere.com'),
        ),
        migrations.AddField(
            model_name='roomevent',
            name='qr_genrate_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='fYyyy', max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='link_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
