# Generated by Django 4.1.5 on 2023-03-15 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer_support", "0002_rename_organization_room_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="authority_portfolio",
        ),
        migrations.AddField(
            model_name="room",
            name="authority_portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer_support.portfolio",
            ),
        ),
    ]
