# Generated by Django 4.1.5 on 2023-03-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_support", "0003_remove_room_authority_portfolio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="side",
            field=models.BooleanField(default=False),
        ),
    ]
