# Generated by Django 4.1.5 on 2023-03-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_support", "0004_message_side"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="email",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="userID",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="username",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
