# Generated by Django 4.1 on 2023-09-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0004_alter_portfolio_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='tvkMW', max_length=200),
        ),
    ]
