# Generated by Django 4.1.5 on 2023-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer_support",
            "0005_portfolio_email_portfolio_phone_portfolio_userid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="dowell_logged_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="sub_product",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="username",
            field=models.CharField(default="Default", max_length=200),
            preserve_default=False,
        ),
    ]
