# Generated by Django 4.1.5 on 2023-04-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_support", "0007_alter_portfolio_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("TEXT", "Text"), ("IMAGE", "Image")],
                default="TEXT",
                max_length=10,
            ),
        ),
    ]
