# Generated by Django 4.1.5 on 2023-04-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer_support", "0008_message_message_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="email",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="username",
        ),
    ]
