# Generated by Django 4.1.5 on 2023-05-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer_support",
            "0009_remove_portfolio_email_remove_portfolio_phone_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="organization",
            field=models.CharField(default="NO_LOGIN", max_length=200),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="portfolio_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="session_id",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="userID",
            field=models.CharField(
                blank=True, default="NO_LOGIN", max_length=200, null=True
            ),
        ),
    ]
