# Generated by Django 4.1.6 on 2023-05-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0010_alter_portfolio_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='authority_portfolio',
            new_name='sender_portfolio',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='N6TyF', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='session_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='userID',
            field=models.CharField(default='NO_LOGIN', max_length=200),
        ),
    ]
