# Generated by Django 4.2.1 on 2023-05-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0010_alter_portfolio_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='wx7X8', max_length=200, unique=True),
        ),
    ]
