# Generated by Django 4.2.1 on 2023-05-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0011_rename_authority_portfolio_room_sender_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='tqjEK', max_length=200),
        ),
    ]
