# Generated by Django 4.2.2 on 2023-07-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0011_rename_authority_portfolio_room_sender_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='S6LwF', max_length=200),
        ),
    ]
