# Generated by Django 4.1.6 on 2023-07-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0016_alter_portfolio_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='pakbH', max_length=200),
        ),
    ]
